# SwiftLint Configuration for NaviNavi
# ADHD-optimized Swift code style rules

# Disabled rules
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for better readability
  - todo # Allow TODO comments for ADHD task management
  - large_tuple # Allow larger tuples for complex data structures

# Opt-in rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Included and excluded paths
included:
  - NaviNavi/NaviNavi
  - NaviNavi/NaviNaviTests
  - NaviNavi/NaviNaviUITests

excluded:
  - NaviNavi/NaviNavi/Assets.xcassets
  - NaviNavi/NaviNavi/Preview Content
  - NaviNavi/Build
  - NaviNavi/DerivedData

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - x
    - y
    - z

# Custom rules for ADHD-friendly code
custom_rules:
  # Encourage descriptive naming for ADHD clarity
  adhd_clarity_naming:
    name: "ADHD Clarity Naming"
    regex: '\b(tmp|temp|data|info|stuff|thing)\b'
    message: "Use descriptive names for better ADHD comprehension"
    severity: warning

  # Encourage breaking down complex conditions
  adhd_simple_conditions:
    name: "ADHD Simple Conditions"
    regex: '(?:&&|\|\|).*(?:&&|\|\|).*(?:&&|\|\|)'
    message: "Consider breaking down complex conditions for better ADHD readability"
    severity: warning

  # Encourage guard statements for clearer code flow
  adhd_guard_usage:
    name: "ADHD Guard Usage"
    regex: 'if\s+.*\s*{\s*return'
    message: "Consider using guard statement for clearer ADHD-friendly code flow"
    severity: warning

# Reporter
reporter: "xcode"